# Daisy Seed project Makefile

TARGET = Daisy_Griesinger_Reverb

CPP_SOURCES = \
main.cpp

# Library locations (adjust if your Daisy checkout lives elsewhere)
LIBDAISY_DIR ?= ../../libDaisy
DAISYSP_DIR ?= ../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
